### PR TITLE
Fix bug, tidy up.

### LINKED ISSUE #27: Internal: listChanges should avoid emitting empty list
A patch was required to land the previous version.

### PR DESCRIPTION
**Pull request by matanlurey**
## 0.20.3

* Bug fix: Avoid emitting an empty list via `ObservableList.listChanges`

Closes https://github.com/dart-lang/observable/issues/27, which was hot-fixed internally.

---

Also adds a few test cases for `listChanges` and restores running `travis.sh` locally.

### CODE REVIEW

File: lib/src/collections/observable_list.dart [hunk 1]
```diff
@@ -217,7 +217,9 @@ class _ObservableDelegatingList<E> extends DelegatingList<E>
 
   @override
   Stream<List<ListChangeRecord<E>>> get listChanges {
```
Comment (kevmoo) [inline lib/src/collections/observable_list.dart]: Make this `=>` while you're at it?

**Review by kevmoo — APPROVED** [review]
:shipit:
